import * as _Array from './Array';
export const Array = _Array;
import * as _Boolean from './Boolean';
export const Boolean = _Boolean;
import * as _Class from './Class';
export const Class = _Class;
import * as _Integer from './Integer';
export const Integer = _Integer;
import * as _Map from './Map';
export const Map = _Map;
import * as _Null from './Null';
export const Null = _Null;
import * as _Number from './Number';
export const Number = _Number;
import * as _Object from './Object';
export const Object = _Object;
import * as _Set from './Set';
export const Set = _Set;
import * as _String from './String';
export const String = _String;
import * as _Type from './Type';
export const Type = _Type;